influxdb:
  image: influxdb
  volumes:
    - ./DOCKER_DATA/influxdb:/var/lib/influxdb
  ports:
    - "8086:8086"
chronograf:
  image: chronograf
  volumes:
    - ./DOCKER_DATA/chronograf:/var/lib/chronograf
  ports:
    - "8083:8888"
  links:
    - influxdb
